EPMDJ-9661 Optimize collections storing
Drill4J/dsm pull request #18
Opened 2022-01-28 10:14 UTC by ViktoriiaLebedeva

2022-01-28 11:03 UTC, Mazel-Tovr commented on src/main/kotlin/Core.kt
> +            entities.add(fff)
```suggestion
            entities.add(json.decodeFromStream(elementSerializer, rs.getBinaryStream(1)))
```

2022-01-28 11:05 UTC, Mazel-Tovr commented on src/main/kotlin/Core.kt
> +        val v = StringBuilder(bufferSize)
```suggestion
        val result = StringBuilder(bufferSize)
```

2022-01-28 11:10 UTC, Mazel-Tovr requested changes

2022-01-28 11:10 UTC, Mazel-Tovr commented on src/main/kotlin/Utils.kt
> +}
```suggestion
fun <T : Any> KClass<T>.customSerializer(
classLoader: ClassLoader,
): KSerializer<T>  = CustomSerializer(this.serializer(), classLoader)

```

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/main/kotlin/Core.kt
> +    val file = File.createTempFile("prefix-", "-postfix")
add // TODO EPMDJ-9370 Remove file creating

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/main/kotlin/serializer/Serializers.kt
> + * Hashcode of the collection item is used as the id.
fix: id of parent

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/main/kotlin/serializer/Serializers.kt
> +class CustomSerializer<T>(
Rename - DsmSerializer

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/main/kotlin/serializer/Serializers.kt
> +                        elementDescriptor.takeIf { it.kind !is PrimitiveKind }?.run {
if-else

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/main/kotlin/serializer/Serializers.kt
> +                            val kClass = classLoader.loadClass(serialName).kotlin
Rename - elementClass

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/main/kotlin/Core.kt
> +): Iterable<T> = transaction {
if ids is empty return empty collection

2022-01-28 12:51 UTC, ViktoriiaLebedeva commented on src/test/kotlin/TestClasses.kt
> +    //todo does't work
remove

2022-01-31 08:18 UTC, Mazel-Tovr commented on src/main/kotlin/Core.kt
> +    if (ids.isEmpty()) return@transaction entities
swap
```suggestion
    if (ids.isEmpty()) return@transaction entities
    val entities: MutableList<T> = mutableListOf()
```
or move this check before creating transaction

2022-01-31 11:35 UTC, LikhanovMaxim commented on src/main/kotlin/Core.kt
> +fun readerToString(value: Reader, maxLength: Int): String? {
add link to copy method 
move to Util

2022-02-02 12:27 UTC, ViktoriiaLebedeva commented on src/main/kotlin/Core.kt
> +    any: Iterable<T>,
rename

2022-02-02 12:27 UTC, ViktoriiaLebedeva commented on src/main/kotlin/Utils.kt
> +fun readerToString(value: Reader, maxLength: Int): String? {
Add test with reading and writing UTF symbols

2022-02-02 12:27 UTC, ViktoriiaLebedeva commented on src/main/kotlin/serializer/Serializers.kt
> +        if (value is BitSet) {
Try to move it in encodeSerializableElement. Add javadoc

2022-02-04 16:29 UTC, Mazel-Tovr commented on src/main/kotlin/serializer/Serializers.kt
> +
What do you think ? 
```suggestion
    override fun serialize(encoder: Encoder, value: T) {
        if (serializer.isBitSetSerializer()) {
            encoder.encodeSerializableValue(String.serializer(), value.stringRepresentation())
        } else {
            serializer.serialize(DsmEncoder(encoder), value)
        }
    }

    override fun deserialize(decoder: Decoder): T {
        if (serializer.isBitSetSerializer()) {
            val decodeSerializableValue = decoder.decodeSerializableValue(String.serializer())
            @Suppress("UNCHECKED_CAST")
            return decodeSerializableValue.toBitSet() as T
        }
        return serializer.deserialize(DsmDecoder(decoder))
    }
  private fun KSerializer<*>.isBitSetSerializer() = serializer.descriptor.serialName == BitSet::class.simpleName
```

2022-02-04 16:38 UTC, ViktoriiaLebedeva commented on src/main/kotlin/serializer/Serializers.kt
> +
Then we have to do cast, but your variant looks better anyway.
`encoder.encodeSerializableValue(String.serializer(), (value as BitSet).stringRepresentation())`

2022-02-08 13:53 UTC, merged